name: AAARRR

on:
  push:
    branches: [ n2 ]
  pull_request:
    branches: [ n2 ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        ./make-aar
        # go vet ./... fails: archive.is/XcDl6
        go install go.uber.org/nilaway/cmd/nilaway@latest
        nilaway ./...
      shell: bash

    - name: Test
      if: success()
      run: |
        # go test -v -race -bench=. -benchtime=100ms ./...
        echo "::notice::success"

      # github.com/actions/upload-artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: firestack-aar-${{ github.sha }}
        path: firestack*.aar
        if-no-files-found: error