name: AAARRR

on:
  push:
    branches: [ n2 ]
  pull_request:
    branches: [ n2 ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup go1.22+
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.22'

    - name: Build
      run: |
        # outputs firestack.aar; also see: "Obj" below
        ./make-aar nogo
      shell: bash

    - name: Test
      if: success()
      run: |
        go env
        # go test -v -race -bench=. -benchtime=100ms ./...
        echo "::notice::success"

    - name: Vet
      run: |
        # github.com/actions/setup-go/issues/27
        export PATH=${PATH}:`go env GOPATH`/bin

        # vet: fails: archive.is/XcDl6
        go vet ./...
        # nilaway
        go install go.uber.org/nilaway/cmd/nilaway@latest
        nilaway ./...
      shell: bash

    - name: Obj
      run: |
        wget --tries=2 --waitretry=3 --no-dns-cache https://github.com/Zxilly/go-size-analyzer/releases/download/v1.0.6/go-size-analyzer_1.0.6_linux_amd64.deb -O gsa.deb
        sudo dpkg -i gsa.deb
        # s/tun2socks.aar/firestack.aar; see: make-aar
        unzip firestack.aar
        gsa jni/arm64-v8a/libgojni.so -f text
      shell: bash

      # github.com/actions/upload-artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: firestack-aar-${{ github.sha }}
        path: firestack*.aar
        if-no-files-found: error

  checker:
    name: Security checker
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    env:
      GO111MODULE: on
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Gosec Scanner
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  # from: github.com/golangci/golangci-lint-action
  golangci-lint:
    name: Linter
    runs-on: ubuntu-latest
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: Allow write access to checks to allow the action to annotate code in the PR.
      checks: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22'
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          args: --config=.golangci.yml --issues-exit-code=0
